version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      # - ./src/logs:/usr/src/app/logs
    networks:
      - my_network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: iqbal
      MONGO_INITDB_ROOT_PASSWORD: iqbal
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  mongo_data:
    driver: local

networks:
  my_network:
    driver: bridge

